### ISSUE TITLE
Quick request/suggestion

### ISSUE THREAD

**Issue by MostHated** [bassmit/lineburst#1]
Hey there,
    I just wanted to throw out a quick request/suggestion for the structure of the repo/package. For folks like myself who love to try out new things, it definitely is helpful if the main repo is a standard Unity project upload that has Assets folder, Packages/manifest, and ProjectSettings with the version so that I can just clone it and open it right up to check it out (if there happens to end up being samples eventually, etc). 

Doing this lets you have the actual package in the Assets folder (or Packages, depending on how you structure things on your end), then you can set up a [github action](https://github.com/instance-id/ElementAnimationToolkit/blob/main/.github/workflows/upm-ci.yml) that automatically takes that standard project repo and creates/updates a [#upm branch](https://github.com/instance-id/ElementAnimationToolkit/tree/upm) automatically when you commit that people can use to import the package straight into the Package Manager in Editor like they would now, just by adding #upm to the url when they paste it into the editor. It ends up being the best of both worlds with very minimal setup. (I did this setup in [one of my repos here](https://github.com/instance-id/ElementAnimationToolkit))

The reason I bring this up in the first place was I just saw your package on OpenUPM and wanted to check it out, but once I clicked on it and saw it was just a package, I thought to myself "ugh.." as I would have to figure out what version is compatible, start a new project with that version, figure out what version of burst to use and install it and etc, etc. Where as with this other setup, all you have to do is commit the project itself, then I just clone it, and boom, good to go. :+1: 

Cheer,
-MH

**Comment by bassmit** [comment]
thanks for the feedback, I'll revisit the setup at some point

**Comment by bassmit** [comment]
Hi MH, do you know of a solution for the Samples? My understanding generally the folder in the package is called Samples~ so that it is ignored and does not cause duplicates when installed. In the unity project it should not be ignored though to allow using the files. I see you skipped the samples feature all together (ie no samples section in package.json)?

**Comment by MostHated** [comment]
Yeah, when I initially set the package up, I was still learning about them and since my package was primarily an editor tool, the majority of the samples that were important were in the editor window anyways, so I didn't bother with it. I should probably revisit that. 

I believe most folks setup that up in a github action, so that when you clone the project and open it in Unity it is just a standard Samples folder, but when it is pushed to the package branch, the folder is renamed automatically to Samples~

**Comment by bassmit** [comment]
yeah I thought so, please let me know if you come across an example action, Im not really sure how to do it so you can keep stacking commits on top of it...

**Comment by MostHated** [comment]
Something along the lines of this should do it:

```yaml
name: CI
on:
  push:
    branches:
    - master
jobs:
  split-upm:
    name: split upm branch (force)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found
        git subtree split -P "$PKG_ROOT" -b upm
        git checkout upm
        if [[ -d "Samples" ]]; then
          git mv Samples Samples~
          rm -f Samples.meta
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "fix: Samples => Samples~"
        fi
        git push -f -u origin upm
      env:
        PKG_ROOT: Packages/package-name
```
